services:
  - type: web
    name: falafel-sales
    runtime: docker
    region: frankfurt
    plan: free
    healthCheckPath: /login
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: LOG_CHANNEL
        value: stderr
